version: '3'
services:
  txstate-mysql:
    build:
      context: .
    depends_on:
      - mysql
  mysql:
    image: mariadb
    logging:
      driver: none
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: default_database
      TZ: America/Los_Angeles
